version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ora
    versions:
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: inquirer
    versions:
    - 7.3.3
